[package]
name = "tdax-pro-rs"
version = "0.1.0"
authors = ["Nattapong Amornbunchornvej <nattapong@chochoe.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
hmac = "0.7"
sha2 = "0.8"
hex = "0.4"